### ISSUE TITLE
[functionality duplication] There are many near duplicate modules for hopelessly outdated IRC daemons

### ISSUE THREAD

**Issue by Xe** [centralchat/omega-services#4]

**Comment by mitchrodrigues** [comment]
This is being rewritten, in corev2, a lot of modules are being purged and removed, in the core refactor/cleanup.

**Comment by Xe** [comment]
Ah, okay. Good to know. Is there an IRC channel or network associated with this project?

**Comment by mitchrodrigues** [comment]
irc.omega-services.org #Omega

**Comment by Xe** [comment]
Thanks much
